//! Document interaction state; document mutations stay in edits.
use crate::app::*;

pub(in crate::app) struct DocumentState {
    pub(in crate::app) document_mode: DocumentMode,
    pub(in crate::app) last_text_cursor: Option<(usize, usize)>,
    pub(in crate::app) text_scroll_pending: bool,
    pub(in crate::app) block_text_editors: Vec<BlockTextEditor>,
    pub(in crate::app) collapsed_scenes: HashSet<String>,
    pub(in crate::app) selected_blocks: HashSet<usize>,
    pub(in crate::app) block_selection_anchor: Option<usize>,
    pub(in crate::app) draft_text: Option<DraftTextBlock>,
    pub(in crate::app) block_drag: crate::app::blocks::BlockDragState,
    pub(in crate::app) block_row_bounds: Rc<RefCell<HashMap<usize, Bounds<Pixels>>>>,
    pub(in crate::app) block_row_positions: RefCell<HashMap<usize, f32>>,
    pub(in crate::app) block_insertion_target: Option<DraftInsertionTarget>,
    pub(in crate::app) block_context_menu: Option<BlockContextMenu>,
    pub(in crate::app) block_context_epoch: usize,
    pub(in crate::app) block_scroll_anchor: ScrollAnchor,
    pub(in crate::app) block_scroll_pending: bool,
    pub(in crate::app) minimap_navigation: minimap::Navigation,
    pub(in crate::app) text_minimap: text_minimap::TextMinimap,
    pub(in crate::app) recovery_epoch: u64,
    pub(in crate::app) syntax_check: Option<gpui_kit::Task<()>>,
    pub(in crate::app) diagnostic_index: std::sync::Weak<crate::authoring::AuthoringIndex>,
    pub(in crate::app) syntax_marks: Option<gpui_kit::base::input::TextDecorationCollection>,
    pub(in crate::app) visual_subscriptions: Vec<Subscription>,
    pub(in crate::app) inline_block_controls: HashMap<usize, InlineBlockControl>,
    pub(in crate::app) block_visible: HashSet<usize>,
    pub(in crate::app) block_heights: HashMap<usize, f32>,
    pub(in crate::app) block_layout: RefCell<crate::app::blocks::layout::Cache>,
    pub(in crate::app) block_height_revision: u64,
    pub(in crate::app) block_text_refresh_pending: bool,
    pub(in crate::app) scene_edit: Option<SceneEditMode>,
    pub(in crate::app) scene_name_input: Entity<InputState>,
    pub(in crate::app) scene_context_menu: Option<SceneContextMenu>,
    pub(in crate::app) scene_context_epoch: u64,
}
